apiVersion: apps/v1
kind: Deployment
metadata:
  name: flone-frontend
  namespace: kavim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flone-frontend
  template:
    metadata:
      labels:
        app: flone-frontend
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: flone-frontend
          image: kavim.azurecr.io/flone-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
